<Project Sdk="Microsoft.NET.Sdk.Web">

    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Swashbuckle.AspNetCore" Version="6.6.2"/>
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\..\..\dotcom\src\Dotcom.Analytics\Dotcom.Analytics.csproj" />
      <ProjectReference Include="..\..\..\dotcom\src\Dotcom.ContentManagement\Dotcom.ContentManagement.csproj" />
      <ProjectReference Include="..\..\..\dotcom\src\Dotcom.Engagement\Dotcom.Engagement.csproj" />
      <ProjectReference Include="..\..\..\dotcom\src\Dotcom.Portfolio\Dotcom.Portfolio.csproj" />
      <ProjectReference Include="..\..\..\mojoSMB\src\mojoSMB.Boundary\mojoSMB.Boundary.csproj" />
      <ProjectReference Include="..\..\..\sigh-tools\src\SighTools.Boundary\SighTools.Boundary.csproj" />
      <ProjectReference Include="..\..\..\syndigator\src\Syndigator.Articles\Syndigator.Articles.csproj" />
      <ProjectReference Include="..\..\..\syndigator\src\Syndigator.FeedProcessing\Syndigator.FeedProcessing.csproj" />
      <ProjectReference Include="..\..\..\syndigator\src\Syndigator.Feeds\Syndigator.Feeds.csproj" />
      <ProjectReference Include="..\..\..\syndigator\src\Syndigator.Reading\Syndigator.Reading.csproj" />
      <ProjectReference Include="..\..\..\syndigator\src\Syndigator.UserProfiles\Syndigator.UserProfiles.csproj" />
      <ProjectReference Include="..\..\..\theCommune\src\TheCommune.Chat\TheCommune.Chat.csproj" />
    </ItemGroup>

</Project>
